config/routes.rb
Rails.application.routes.draw do
  
root 'depts#index'

  resources :depts do 
    resources :items
  end
  resources :items do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dept.rb
class Dept < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :dept
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  before_save :check_author
  belongs_to :item

  def check_author
    if self.author.blank?
      self.author = 'anon'
    end
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/depts_controller.rb
class DeptsController < ApplicationController
  before_action :set_dept, only: [:show, :edit, :destroy, :update]

  def index
    @depts = Dept.all
  end

  def new
    @dept = Dept.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @dept = Dept.new(dept_params)
    if @dept.save
      redirect_to depts_path
    else
      render :new
  end
end

  def show
  end 

  def update
    if @dept.update(dept_params)
      redirect_to @dept
    else
      render :edit
    end
  end

  def destroy
    @dept.destroy
    redirect_to depts_path
  end

  private
    def set_dept
    @dept = Dept.find(params[:id])
    end

    def dept_params
    params.require(:dept).permit(:business)
    end
  end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_dept
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @dept.items
  end

  def show
  end

  def new
    @item = @dept.items.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @item = @dept.item.new(item_params)
    if @item.save
      redircet_to [@dept, @item]
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redircet_to [@dept, @item]
    else
      render :edit
    end
  end
  
  def destroy
    @item.destroy
    redircet_to dept_items_path
  end

   private

  def set_dept
    @dept = Dept.find(params[:dept_id])
  end
  def set_item
    @item = Item.find(params[:id])
  end
  def item_params
    params.require(:item).permit(:product, :price, :discription)

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_item

  def new
    @review = review.new
  end

  def create
    @review = @item.reviews.new(review_params)
    if @review.save
      redirect_to dept_item_path(@item.dept_id, @item)
    else
      render :new
    end
  end

  private
    def set_item
      @item = Item.find(params[:item_id])
    end

    def review_params
      params.require(:review).permit(:body, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/depts/_form.html.erb
<h1><%= @dept.id ? 'Edit Business' : 'Create Business' %></h1> <%# Ternary if dept id exist then edit else create%>
<hr />
<%= form_for @dept do |f| %>
  <%= f.label :business %>
  <%= f.text_field :business, required: true, autofocus: true %>

  <%= f.label :type %>
  <%= f.text_field :type, required: true %>

  <%= f.label :phone %>
  <%= f.text_field :phone, required: true %>

  <%= f.label :email %>
  <%= f.text_field :email, required: true %>

  <%= f.label :hours %>
  <%= f.text_field :hours, required: true %>

  <%= f.submit %>
<% end %>

app/views/depts/index.html.erb
<h1>My Childhood Mall</h1>
<hr />
<h2>Click a Business To View Content</h2>
<%= link_to 'Create a New Business', new_dept_path %>
<ul>
  <% @depts.each do |dept| %>
    <li><%= link_to dept.business, dept %></li>
  <% end %>
</ul

app/views/depts/show.html.erb
 <h1><%= @dept.business %></h1>
<hr />
<p> <%= @dept.type %> </p>
<p> <%= @dept.phone %> </p>
<p> <%= @dept.email %> </p>
<p> <%= @dept.hours %> </p>
<p>What would you like to do?</p>
<%= link_to 'View Merchandise', dept_items_path(@dept) %>
<br />
<%= link_to 'Edit Business', edit_dept_path(@dept) %>
<br />
<%= link_to 'Delete Business', @dept, method: :delete %>
<br/>
<%= link_to 'Back', depts_path%>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit item' : 'Create item' %></h1>
<hr />
<%= form_for [@sub, @item] do |f| %>
  <%= f.label :product %>
  <%= f.text_field :product required: true, autofocus: true %>
  <br />
  <%= f.label :price %>
  <%= f.text_area :price, required: true %>
  <br />
  <%= f.label :discription %>
  <%= f.text_area :discription required: true %>
  <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1>Click To View Item</h1>
<%= link_to 'Create a new item', new_dept_item_path(@dept) %>
<ul>
  <%# @items.depts.each do |item| %> 
    <li><%= link_to Item.product, [@dept, item]%>
    </li> 
</ul>
  <%# end %>

app/views/items/show.html.erb
<h1><%= @dept.name %> - <%= @item.name %></h1>
<p><%= @item.discription %></p>
<h2>Comments</h2>
<hr/>
<% @item.reviews.each do |review| %>
  <%= render 'reviews/review', { review: review } %>
<% end %>
<%= link_to 'Edit Product', edit_dept_item_path([@dept, @item]) %>
<%= link_to 'Delete Product', [@dept, @item], method: :delete %>
<%= link_to "Back To Product", dept_items_path(@dept) %>
<%= link_to 'Add Review', new_item_review_path(@item) %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%# link_to 'About', about_path %>
<%# link_to 'Pages', pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeptStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/reviews/_review.html.erb
<hr />
<p>Author: <%= review.author %></p>
<p><strong><%= review.body %></strong></p>
</hr>

app/views/reviews/new.html.erb
<h1>Add A Review</h1>
<%= form_for [@item, @review] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author, placeholder: 'Leave Blank To Remain Anonymous' %>
  <br />
  <%= f.submit %>
<% end %>